path: /home/bsa/Projects/UniformDetect/data

train: images/train

val: images/train

names:
  0: бортпроводник_ж
  1: платье
  2: блуза_кор_брюки
  3: блуза_жакет_брюки
  4: пилотка
  5: шейный_платок
  6: жакет
  7: бейдж
  8: пропуск
  9: ремень
  10: блуза_кор_юбка
  11: блуза_жакет_юбка
  12: блуза_кор_жилет_кост_юбка
  13: туфли
  14: плащ
  15: пальто
  16: шапка_зима
  17: шарф
  18: перчатки
  19: сапоги
  20: колготы
  21: нижнее_бельё
  22: кольцо
  23: серьги
  24: цепочка_нарушение
  25: зажим_галстук
  26: часы
  27: очки
  28: линзы
  29: сумка
  30: зонт
  31: жилет_тр
  32: платье_жакет
  33: шейный_платок_нарушение
  34: часы_нарушение
  35: браслет_нарушение
  36: колготы_нарушение
  37: туфли_нарушение
  38: серьги_нарушение
  39: пирсинг_нарушение
  40: жакет_нарушение
  41: блузка_кор_жилет_тр_юбка_нарушение
  42: расстёгнутая_одежда_нарушение
  43: блуза_кор_брюки_жилет_тр
  44: блуза_кор_брюки_жилет_кост
  45: блуза_кор_брюки
  46: блуза_дл_жилет_тр_брюки
  47: блуза_дл_жилет_кост_брюки
  48: блуза_дл_жилет_тр_юбка
  49: предмет_в_кармане_нарушение
  50: неопрятно_нарушение
  51: грязь_повреждение_нарушение
  52: жилет_кост
  53: лицо

colors:
  0:
    - 74
    - 148
    - 68
  1:
    - 74
    - 148
    - 68
  2:
    - 74
    - 148
    - 68
  3:
    - 74
    - 148
    - 68
  4:
    - 74
    - 148
    - 68
  5:
    - 74
    - 148
    - 68
  6:
    - 74
    - 148
    - 68
  7:
    - 74
    - 148
    - 68
  8:
    - 74
    - 148
    - 68
  9:
    - 74
    - 148
    - 68
  10:
    - 74
    - 148
    - 68
  11:
    - 74
    - 148
    - 68
  12:
    - 74
    - 148
    - 68
  13:
    - 74
    - 148
    - 68
  14:
    - 74
    - 148
    - 68
  15:
    - 74
    - 148
    - 68
  16:
    - 74
    - 148
    - 68
  17:
    - 74
    - 148
    - 68
  18:
    - 74
    - 148
    - 68
  19:
    - 74
    - 148
    - 68
  20:
    - 74
    - 148
    - 68
  21:
    - 74
    - 148
    - 68
  22:
    - 74
    - 148
    - 68
  23:
    - 74
    - 148
    - 68
  24:
    - 58
    - 30
    - 196
  25:
    - 74
    - 148
    - 68
  26:
    - 74
    - 148
    - 68
  27:
    - 74
    - 148
    - 68
  28:
    - 74
    - 148
    - 68
  29:
    - 74
    - 148
    - 68
  30:
    - 74
    - 148
    - 68
  31:
    - 74
    - 148
    - 68
  32:
    - 74
    - 148
    - 68
  33:
    - 58
    - 30
    - 196
  34:
    - 58
    - 30
    - 196
  35:
    - 58
    - 30
    - 196
  36:
    - 58
    - 30
    - 196
  37:
    - 58
    - 30
    - 196
  38:
    - 58
    - 30
    - 196
  39:
    - 58
    - 30
    - 196
  40:
    - 58
    - 30
    - 196
  41:
    - 58
    - 30
    - 196
  42:
    - 58
    - 30
    - 196
  43:
    - 74
    - 148
    - 68
  44:
    - 74
    - 148
    - 68
  45:
    - 74
    - 148
    - 68
  46:
    - 74
    - 148
    - 68
  47:
    - 74
    - 148
    - 68
  48:
    - 74
    - 148
    - 68
  49:
    - 58
    - 30
    - 196
  50:
    - 58
    - 30
    - 196
  51:
    - 58
    - 30
    - 196
  52:
    - 74
    - 148
    - 68
  53:
    - 74
    - 148
    - 68

model_names:
  - Свёрточная нейронная сеть (CNN)
  - Алгоритм_1

model_files:
  - yolo8.pt
  - yolov8n.pt

uniform:
  Ботпроводник(ж) лето комплект 1:
    - пилотка
    - бортпроводник_ж
  Ботпроводник(ж) лето комплект 2:
    - бортпроводник_ж
    - пилотка
    - платье
    - бейдж
    - туфли
    - шейный_платок
    - часы
    - колготы

uniform_consist:
  - бортпроводник_ж
  - жакет
  - платье
  - юбка
  - брюки
  - блуза
  - блуза_дл
  - блуза_кор
  - жилет_кост
  - жилет_тр
  - пилотка
  - ремень
  - шейный_платок
  - туфли
  - бейдж
  - пропуск
  - часы
  - колготы
  - серьги
  - кольцо
  - плащ
  - пальто
  - шапка_зима
  - шарф
  - перчатки
  - сапоги
  - зажим_галстук
  - очки
  - линзы
  - сумка
  - зонт
